export const mockdata = [
    {
        id: 1,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602569085_7c3e90155a66a2f220b7.png',
        date: '13 Oktober 2020',
        title: 'Pasangan Calon Ketua Wakil Ketua SEMA Polstat STIS',
        excerpt: 'Rabu (29/7), telah dibuka pendaftaran Calon Ketua dan Wakil Ketua Senat Mahasiswa Politeknik Statistika STIS. Calon Ketua Senat Mahasiswa merupakan mahasiswa tingkat 4 sedangkan...',
        description: '',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 2,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602580730_bb96681ea32afbfd92a5.png',
        date: '13 Oktober 2020',
        title: 'Tahapan Seleksi Cakawaka Sema',
        excerpt: 'Sebelum memasuki masa kampanye Cakawaka Sema, telah dilaksanakan berbagai tahapan seleksi untuk mendapatkan bakal calon terbaik. Tahap pertama berupa seleksi berkas yang diikuti oleh seluruh paslon yang akan mengikuti Pemira 2020. Berkas dikumpulkan dalam bentuk softfile yang terdiri dari transkip nilai...',
        description: '',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 3,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602584692_524a9dc1caa5953b0fde.png',
        date: '13 Oktober 2020',
        title: 'Pemilihan Ketua Kelas atau Anggota DPM Periode 2020',
        excerpt: 'Pemilihan ketua kelas telah berlangsung mulai dari tanggal 31 Agustus hingga 8 September untuk tingkat 2-4 dan 6 hingga 7 Oktober untuk tingkat 1. Prosedur yang dilaksanakan adalah calon ketua kelas mendaftar di Google Form yang disediakan panitia beberapa hari sebelum pemilihan. Kemudian PJ masing-masing...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 4,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602588118_0faee0d8cf331e4d6918.png',
        date: '13 Oktober 2020',
        title: 'Kampanye Akbar 2020',
        excerpt: 'Dalam memilih seorang pemimpin, kita harus mengenal siapa calon pemimpin kita dengan mengetahui visi misi, progam, dan janji mereka. Dengan mengetahui siapa calon pemimpin kita, tentu kita akan yakin dan tidak menyesal ketika memilih mereka dalam Pemilihan Raya 2020 nanti. Bagaimana cara kita mengenal...',
        description: '',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 5,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1607072778_30f25fc3d4f096d5ce1a.png',
        date: '04 Desember 2020',
        title: 'Musyawarah DPM dan Hasil Pemilihan Ketua DPM Periode 2020-2021',
        excerpt: 'Dewan Perwakilan Mahasiswa (DPM) merupakan perubahan bentuk dari Badan Perwakilan Mahasiswa (BPM) dan Majelis Permusyawaratan Mahasiswa (MPM) yang menjalankan fungsi legislatif Imapolstat dan salah satu pemegang kekuasaan tertinggi dalam Imapolstat melalui Sidang Umum DPM. DPM menyalurkan aspirasi dari...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 6,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1627698105_2403e7b73b60343e5d0c.jpg',
        date: '30 Juli 2020',
        title: 'DPM Polstat STIS Tetapkan Ketetapan mengenai Pemira',
        excerpt: 'Dewan Perwakilan Mahasiswa (DPM) resmi menetapkan Ketetapan Dewan Perwakilan Mahasiswa Politeknik Statistika STIS Nomor 003/DPM/2021 tentang Pemilihan Raya pada 17 Juli 2021. Ketetapan tersebut ditetapkan oleh Ketua DPM periode 2020/2021, Septriyan Machsus. Selain ditetapkan, Tap DPM Polstat STIS Nomor...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 7,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1629349447_1a2d24cd3c6a4dc6f0a6.jpeg',
        date: '19 Agustus 2021',
        title: 'Peraturan Panitia Pemilihan Raya tentang Penyelenggaran Pemira',
        excerpt: 'Senin (02/08) Ketua Panitia Pemilihan Raya (Papera), Andi Alfitra Putra Fadila menetapkan peraturan Papera tentang Penyelenggaraan Pemilihan Raya (Pemira) Nomor: 001/PAPERA/2021. Peraturan tersebut resmi diundangkan oleh ekretaris I Dewan Perwakilan Mahasiswa, Neisya Aulia Fijri. Peraturan Papera...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 8,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1630813091_277e32d71b0942fd63a4.png',
        date: '04 September 2021',
        title: 'Pemilihan Ketua Kelas atau Anggota DPM Periode 2021',
        excerpt: 'Periode Pemilihan Ketua Kelas (PKK) Tingkat I-IV Periode 2021/2022 telah berlangsung selama empat hari, sejak Senin (23/8) hingga Kamis (26/8). PKK dilaksanakan di ruang virtual Zoom atau Google Meet dengan dua Panitia Pemilihan Raya (Papera) yang menjadi penanggung jawab tiap kelas. Setiap penanggung...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 9,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1631538365_063516e4ed008cd4381f.png',
        image_2: '',
        date: '13 September 2021',
        title: 'Musyawarah Besar I DPM Polstat STIS Periode 2021 2022',
        excerpt: 'Musyawarah Besar I Dewan Perwakilan Mahasiswa (DPM) Polstat STIS periode 2021/2022 telah dilaksanakan pada Sabtu (04/09). Seperti tahun lalu, Musyawarah Besar kali ini dilakukan...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 10,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1631538950_f606746ecc0d0f0e70cf.png',
        image_2: '',
        date: '13 September 2021',
        title: 'Musyawarah Besar II DPM Polstat STIS Periode 2021 2022',
        excerpt: 'Musyawarah Besar I Dewan Perwakilan Mahasiswa (DPM) Polstat STIS periode 2021/2022 telah dilaksanakan pada Minggu (12/09) dengan dihadiri seluruh anggota DPM periode 2021/2022...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 11,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1662252162_431bfc766444f3fcb335.jpg',
        image_2: '',
        date: '3 September 2022',
        title: 'Publikasi Pemilihan Raya Cakawaka Sema 2022 2023 Putaran Pertama',
        excerpt: 'Pemilihan Ketua Sema Periode 2022/2023 putaran pertama telah dilaksanakan selama 2 hari, yaitu sejak tanggal 29 Agustus 2022 hingga 30 Agustus 2022. Pemilihan ini dilaksanakan...',
        description: '',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 12,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1662552369_1ddbfe224f8c501fcaec.jpg',
        image_2: '',
        date: '7 September 2022',
        title: 'Musyawarah Final Dewan Perwakilan Mahasiswa Periode 2022 2023',
        excerpt: 'Pada Senin, 05 September 2022, seluruh anggota Dewan Perwakilan Mahasiswa Politeknik Statistika STIS periode 2022/2023 telah menyelenggarakan  kegiatan Musyawarah Final DPM...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 13,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1663162795_85e31a12f8132b614ffe.jpg',
        image_2: '',
        date: '19 September 2022',
        title: 'Publikasi Pemilihan Raya Cakawaka Sema 2022 2023 Putaran Kedua',
        excerpt: 'Pemilihan Ketua-Wakil Ketua Sema Periode 2022/2023 putaran kedua telah dilaksanakan selama dua hari, yaitu pada tanggal 5 - 6 September 2022. Berbeda dengan pemilihan putaran...',
        description: '',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 14,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1663990822_a47f93e4175d7859f5c8.jpg',
        image_2: '',
        date: '23 September 2022',
        title: 'Pelantikan DPM dan Kawaka Sema Periode 2022 2023',
        excerpt: 'Setelah melalui rangkaian proses seleksi, DPM dan Ketua-Wakil Ketua Sema terpilih Politeknik Statistika STIS periode 2022/2023 pun resmi dilantik. Kegiatan pelantikan ini...',
        description: '',
        tags: 'DPM, SEMA',
        author: 'HPD',
    },
];