export const mockdata = [
    {
        id: 1,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602569085_7c3e90155a66a2f220b7.png',
        date: '13 Oktober 2020',
        title: 'Pasangan Calon Ketua Wakil Ketua SEMA Polstat STIS',
        excerpt: 'Rabu (29/7), telah dibuka pendaftaran Calon Ketua dan Wakil Ketua Senat Mahasiswa Politeknik Statistika STIS. Calon Ketua Senat Mahasiswa merupakan...',
        description: {
            paragraph_1:'Rabu (29/7), telah dibuka pendaftaran Calon Ketua dan Wakil Ketua Senat Mahasiswa Politeknik Statistika STIS. Calon Ketua Senat Mahasiswa merupakan mahasiswa tingkat 4 sedangkan Calon Wakil Ketua Senat Mahasiswa merupakan mahasiswa tingkat 3. Seluruh mahasiswa tingkat 3 dan 4 yang memenuhi syarat untuk mendaftar berhak untuk mengajukan diri dan mendaftar melalui PPDS (Panitia Pemilihan DPM dan SEMA). Pendaftaran ditutup pada Sabtu (22/8).',
            paragraph_2: 'Setelah melalui seleksi berkas dan kelayakan (fit & proper test), didapatkan 3 pasangan calon yang layak bersaing pada Pemilihan Raya Senat Mahasiswa Politeknik Statistika STIS. Pasangan calon tersebut, antara lain :\n\n',
            paragraph_3: '1. Regy Alvapin dan Dimas Hutomo\n\n2. Fachrizal Safriel dan M. Nur Megantoro\n\n3. M. Irfan Zulfahmi dan Andi Alfitra.\n\n',
            paragraph_4: 'Dengan demikian, para pasangan calon harus melewati beberapa kegiatan sebelum pemilihan dilakukan, seperti Masa Kampanye, Kampanye Akbar, dan Diskusi Panel.',
            paragraph_5:'',
        },
        paragraph_add:'',
        paragraph_footer:'',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 2,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602580730_bb96681ea32afbfd92a5.png',
        image_2: 'https://pemira.stis.ac.id/assets/img/postingan/1602580479_b8ef15e9765c85742b80.jpg',
        date: '13 Oktober 2020',
        title: 'Tahapan Seleksi Cakawaka Sema',
        excerpt: 'Sebelum memasuki masa kampanye Cakawaka Sema, telah dilaksanakan berbagai tahapan seleksi untuk mendapatkan bakal calon terbaik. Tahap pertama berupa...',
        description: {
            paragraph_1: 'Sebelum memasuki masa kampanye Cakawaka Sema, telah dilaksanakan berbagai tahapan seleksi untuk mendapatkan bakal calon terbaik. Tahap pertama berupa seleksi berkas yang diikuti oleh seluruh paslon yang akan mengikuti Pemira 2020. Berkas dikumpulkan dalam bentuk softfile yang terdiri dari transkip nilai IP, surat pernyataan, sertifikat Latihan Dasar Kepemimpinan hingga foto 100 KTM/Kartu asuransi/badge/tangkapan layar profil akun Sipadu yang mendukung bakal pasangan calon.\n\n',            
            paragraph_2: 'Tahap berikutnya adalah Fit and Proper Test yang terdiri dari tes tetulis dan tes wawancara yang dilakukan oleh dosen dan panitia. Fit and Proper Test bertujuan untuk memperoleh Cakawaka Sema yang kompeten dan bertanggung jawab. Aspek yang diuji pada tahap ini meliputi aspek ideologi dan dasar negara, loyalitas dan kepemimpian, pengetahuan seputar kampus dan BPS, serta sifat Profesional, Integritas, dan Amanah. Tes tertulis dilaksanakan pada tanggal 10 September 2020 melalui Google Classroom. Selanjutnya tes wawancara diselenggarakan secara virtual melalui media Zoom. Wawancara dilaksanakan pada tanggal 11 September 2020 dengan menghadirkan dosen Politeknik Statistika STIS sebagai pewawancara. Dosen yang terlibat menjadi pewawancara adalah Siskarossa Ika Oktora, SST, M. Stat. dan Yaya Setiadi, SST, M.M., M.Pd..\n\n',
            paragraph_3: 'Paslon yang telah berhasil melewati dan memenuhi berbagai tahapan di atas mengikuti pengundian nomor urut Paslon Kawaka Sema yang diadakan oleh PPDS.',
            paragraph_4:'',
            paragraph_5:'',
        },  
        paragraph_add:'',
        paragraph_footer:'',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 3,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602584692_524a9dc1caa5953b0fde.png',
        image_2: 'https://pemira.stis.ac.id/assets/img/postingan/1602584490_88ca40c4fdb4c70325a9.png',
        date: '13 Oktober 2020',
        title: 'Pemilihan Ketua Kelas atau Anggota DPM Periode 2020',
        excerpt: 'Pemilihan ketua kelas telah berlangsung mulai dari tanggal 31 Agustus hingga 8 September untuk tingkat 2-4 dan 6 hingga 7 Oktober untuk...',
        description: {
            paragraph_1: '"Keberhasilan pemimpin diukur dari kemampuan mereka dalam menyejahterakan umat yang mereka pimpin." - Abdurrahman Wahid \n\n',
            paragraph_2: 'Pemilihan ketua kelas telah berlangsung mulai dari tanggal 31 Agustus hingga 8 September untuk tingkat 2-4 dan 6 hingga 7 Oktober untuk tingkat 1. Prosedur yang dilaksanakan adalah calon ketua kelas mendaftar di Google Form yang disediakan panitia beberapa hari sebelum pemilihan. Kemudian PJ masing-masing kelas akan menghubungi salah satu anggota kelas untuk menyampaikan kepada seluruh anggota kelas yang lain bahwa akan diadakan pemilihan ketua kelas secara daring pada waktu yang telah ditetapkan.\n\n',
            paragraph_3: 'Pemilihan ketua kelas melalui media Zoom memiliki susunan acara sebagai berikut : Pembacaan SOP Pemilihan Ketua Kelas, penyampaian visi misi oleh calon Ketua Kelas, voting melalui fitur raise hand maupun Private Chat, dan pembentukan struktur organisasi kelas yang dipimpin langsung oleh Ketua Kelas terpilih. Calon ketua kelas yang menyampaikan visi misi berjumlah minimal dua orang, jika kurang dari itu maka anggota kelas harus mengusulkan nama-nama yang dikira mampu mengemban amanah sebagai ketua kelas tanpa ada unsur keterpaksaan. Ketua kelas terpilih merupakan calon dengan perolehan suara lebih dari lima puluh persen dari jumlah anggota kelas yang hadir pada saat pemilihan.\n\n',
            paragraph_4: 'Ketua kelas terpilih akan secara otomatis menjadi anggota Dewan Perwakilan Mahasiswa (DPM) Periode 2020/2021. Hal ini disebabkan karena salah satu tugas DPM adalah menyalurkan aspirasi mahasiswa, maka dari itu untuk mempermudah penyaluran aspirasi tersebut dibutuhkan perwakilan dari setiap kelas. Sehingga, ketua kelas dianggap sebagai perwakilan kelas dan otomatis menjadi anggota DPM. Selanjutnya, seluruh anggota DPM dari tingkat 1-4 akan melakukan Sidang Pemilihan Ketua DPM periode 2020/2021.',
            paragraph_5:'',
        },
        paragraph_add:'',
        paragraph_footer:'',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 4,
        image: 'https://pemira.stis.ac.id/assets/img/cover/1602588118_0faee0d8cf331e4d6918.png',
        image_2: 'https://pemira.stis.ac.id/assets/img/postingan/1602588945_1f8a9c5ad35242b85d17.png',
        date: '13 Oktober 2020',
        title: 'Kampanye Akbar 2020',
        excerpt: 'Dalam memilih seorang pemimpin, kita harus mengenal siapa calon pemimpin kita dengan mengetahui visi misi, progam, dan janji mereka. Dengan mengetahui...',
        description: {
            paragraph_1: 'Dalam memilih seorang pemimpin, kita harus mengenal siapa calon pemimpin kita dengan mengetahui visi misi, progam, dan janji mereka. Dengan mengetahui siapa calon pemimpin kita, tentu kita akan yakin dan tidak menyesal ketika memilih mereka dalam Pemilihan Raya 2020 nanti. Bagaimana cara kita mengenal paslon yg akan dipilih di Pemilihan Raya 2020 nanti? Nah, Kampanye akbar inilah yang menjadi salah satu cara untuk mengenal paslonnya.\n\n',
            paragraph_2: 'Kampanye akbar sendiri merupakan salah satu bentuk fasilitas dari PPDS kepada Paslon Kawaka SEMA yang bertujuan agar setiap Paslon Kawaka SEMA dapat berorasi dan mendapatkan dukungan dari mahasiswa/i Politeknik Statistika STIS. Kampanye akbar dilakukan sesuai ketentuan yang telah ditetapkan dan dilaksanakan secara bertanggung jawab, karena ini merupakan wadah untuk meningkatkan partisipasi pemilih dalam Pemira  serta mewujudkan Pemira yang berkualitas.\n\n',
            paragraph_3: 'Kampanye akbar dimulai dari tanggal 7 Oktober dengan Paslon nomor urut 1, 8 Oktober oleh Paslon nomor urut 2 hingga diakhiri oleh Paslon nomor urut 3 pada 9 Oktober dan dilaksanakan pada pukul 16.15 sampai 17.30 WIB. Paslon dan tim suksesnya akan mempromosikan visi misi, hingga program kerja unggulan dari masing-masing Paslon. Dalam kampanye Akbar diadakan pula tanya jawab terbuka antar peserta dan Paslon yang turut memeriahkan kampanye akbar 2020.\n\n',
            paragraph_4: 'Kampanye akbar diharapkan dapat dimanfaatkan dengan baik bagi para pemilih saat Pemilihan Raya 2020 nanti, karena satu suara dari pemilih akan sangat menentukan bagaimana nasib di masa mendatang.\n\n',
            paragraph_5: '“A true leader is not the one with the most followers, but one who creates the most leaders.” - Neale Donald Walsch.'
        },  
        paragraph_add:'',
        paragraph_footer:'',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 5,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1607072778_30f25fc3d4f096d5ce1a.png',
        image_2: 'https://pemira.stis.ac.id/assets/img/postingan/1607072720_a2eec642b0f03978fa41.png',
        date: '04 Desember 2020',
        title: 'Musyawarah DPM dan Hasil Pemilihan Ketua DPM Periode 2020-2021',
        excerpt: 'Dewan Perwakilan Mahasiswa (DPM) merupakan perubahan bentuk dari Badan Perwakilan Mahasiswa (BPM) dan Majelis Permusyawaratan Mahasiswa (MPM) yang...',
        description: {
            paragraph_1: 'Dewan Perwakilan Mahasiswa (DPM) merupakan perubahan bentuk dari Badan Perwakilan Mahasiswa (BPM) dan Majelis Permusyawaratan Mahasiswa (MPM) yang menjalankan fungsi legislatif Imapolstat dan salah satu pemegang kekuasaan tertinggi dalam Imapolstat melalui Sidang Umum DPM. DPM menyalurkan aspirasi dari seluruh anggota Imapolstat yang dalam hal ini adalah mahasiswa/i Politeknik Statistika STIS secara keseluruhan, baik yang berkaitan dengan kinerja Sema maupun kepada Pimpinan Politeknik Statistika STIS.\n\n',
            paragraph_2: 'Pelaksanaan pemilihan Dewan Perwakilan Mahasiswa (DPM) Periode 2020/2021 telah dilaksanakan mulai pendaftaran calon ketua kelas tingkat I,II,III,IV yang selanjutnya akan menjadi Anggota DPM, Pemilihan Anggota DPM, dan Musyawarah DPM untuk mencapai keputusan final dalam pemilihan Ketua DPM Periode 2020/2021.\n\nMusyawarah DPM awal yang dilaksanakan pada Jumat (18/9), dan Musyawarah DPM Final pada Sabtu (10/10) dilaksanakan via Zoom Meeting dan dihadiri oleh seluruh anggota DPM dan PPDS sebagai Panitia Penyelenggara.\n\nMusyawarah DPM awal dengan 3 calon ketua DPM, yaitu\n\n',
            paragraph_3: '1. Septriyan Machsus\n\n2. Iqbal Mukti Pratama\n\n3. Yusril Abdul Aziz\n\n',
            paragraph_4: 'Kemudian pada hasil Musyawarah DPM final telah ditetapkan yang menjadi Ketua DPM Periode 2020/2021 adalah Septriyan Machsus (4SE5).',
            paragraph_5: ''
        },
        paragraph_add:'',
        paragraph_footer:'',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 6,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1627698105_2403e7b73b60343e5d0c.jpg',
        date: '30 Juli 2020',
        title: 'DPM Polstat STIS Tetapkan Ketetapan mengenai Pemira',
        excerpt: 'Dewan Perwakilan Mahasiswa (DPM) resmi menetapkan Ketetapan Dewan Perwakilan Mahasiswa Politeknik Statistika STIS Nomor 003/DPM/2021 tentang Pemilihan...',
        description: {
            paragraph_1: 'Dewan Perwakilan Mahasiswa (DPM) resmi menetapkan Ketetapan Dewan Perwakilan Mahasiswa Politeknik Statistika STIS Nomor 003/DPM/2021 tentang Pemilihan Raya pada 17 Juli 2021. Ketetapan tersebut ditetapkan oleh Ketua DPM periode 2020/2021, Septriyan Machsus. Selain ditetapkan, Tap DPM Polstat STIS Nomor 003/DPM/2021 juga diundangkan dengan menempatkannya dalam Lembar Organisasi Mahasiswa Imapolstat agar setiap orang mengetahuinya. Ketetapan tersebut diundangkan oleh Sekretaris I DPM periode 2020/202, Neisya Aulia Fijri pada 17 Juli 2021.\n\n',
            paragraph_2: 'Tap DPM Polstat STIS Nomor 003/DPM/2021 dibentuk sebagai dasar yang mengatur jalannya Pemilihan Raya Politeknik Statistika STIS (Pemira). Pemira merupakan sarana untuk memilih Ketua dan Wakil Ketua Senat Mahasiswa, Ketua DPM, Ketua Kelas, dan Ketua Tingkat I-IV sebagai perwujudan kedaulatan mahasiswa.\n\nTap DPM Polstat STIS Nomor 003/DPM/2021 terdiri dari 98 pasal. Adapun pasal-pasal tersebut terdapat dalam beberapa bab sebagai berikut:\n',
            paragraph_3: '(1) Bab I Ketentuan Umum,\n(2) Bab II Asas dan Tujuan,\n(3) Bab III Penyelenggara Pemilihan Raya,\n(4) Bab IV Pelaksanaan Pemira,\n(5) Bab V Penetapan Hasil Pemira,\n(6) Bab VI Pemira Lanjutan dan Pemira Susulan,\n(7) Bab VII Pelanggaran dan Larangan Pemira,\n(8) Bab VIII Perselisihan Hasil Pemira, dan\n(9) Bab IX Penutup.\n\n',
            paragraph_4: 'Tap DPM Polstat STIS Nomor 003/DPM/2021 mulai berlaku sejak tanggal ditetapkan dan diharapkan dapat dijadikan dasar dalam menjalankan Pemira dengan sebaik-baiknya.',
            paragraph_5:'',
        },
        paragraph_add:'',
        paragraph_footer:'',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 7,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1629349447_1a2d24cd3c6a4dc6f0a6.jpeg',
        date: '19 Agustus 2021',
        title: 'Peraturan Panitia Pemilihan Raya tentang Penyelenggaran Pemira',
        excerpt: 'Senin (02/08) Ketua Panitia Pemilihan Raya (Papera), Andi Alfitra Putra Fadila menetapkan peraturan Papera tentang Penyelenggaraan Pemilihan Raya (Pemira) Nomor...',
        description: {
            paragraph_1: 'Senin (02/08) Ketua Panitia Pemilihan Raya (Papera), Andi Alfitra Putra Fadila menetapkan peraturan Papera tentang Penyelenggaraan Pemilihan Raya (Pemira) Nomor: 001/PAPERA/2021. Peraturan tersebut resmi diundangkan oleh Sekretaris I Dewan Perwakilan Mahasiswa, Neisya Aulia Fijri.\n\n',
            paragraph_2: 'Peraturan Papera ditetapkan agar setiap orang mengetahuinya, memerintahkan pengundangan peraturan Papera ini dengan penempatannya dalam berita acara Organisasi Imapolstat. Beberapa hal yang menjadi penimbangan dalam penetapan peraturan Papera adalah sebagai berikut:\n',
            paragraph_3: '1. bahwa Pemilihan Raya merupakan sarana untuk mewujudkan kedaulatan mahasiswa sebagaimana diamanatkan dalam Anggaran Dasar dan Anggaran Rumah Tangga Ikatan Mahasiswa Politeknik Statistika STIS untuk memilih Ketua Senat Mahasiswa dan Wakil Ketua Senat Mahasiswa, Ketua Dewan Perwakilan Mahasiswa, Ketua Kelas, dan Ketua Tingkat I-IV;\n2. bahwa diperlukan pengaturan Pemilihan Raya sebagai perwujudan kegiatan demokrasi yang berintegritas dengan menjamin konsistensi dan kepastian hukum yang efektif dan efisien;\n3. bahwa Pemilihan Raya wajib menjamin tersalurkannya suara mahasiswa secara langsung, umum, bebas, rahasia, jujur, adil;\n\n',
            paragraph_4:'Adapun isi dari peraturan Papera terdiri dari 17 pasal dalam 5 bab. Dengan diundangkan peraturan tersebut maka peraturan Papera mulai berlaku dan diharapkan dapat dijadikan dasar dalam menjalankan Pemira dengan sebaik-baiknya.',
            paragraph_5:'',
        },
        paragraph_add:'',
        paragraph_footer:'',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 8,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1630813091_277e32d71b0942fd63a4.png',
        date: '04 September 2021',
        title: 'Pemilihan Ketua Kelas atau Anggota DPM Periode 2021',
        excerpt: 'Periode Pemilihan Ketua Kelas (PKK) Tingkat I-IV Periode 2021/2022 telah berlangsung selama empat hari, sejak Senin (23/8) hingga Kamis (26/8). PKK dilaksanakan di...',
        description: {
            paragraph_1: 'Periode Pemilihan Ketua Kelas (PKK) Tingkat I-IV Periode 2021/2022 telah berlangsung selama empat hari, sejak Senin (23/8) hingga Kamis (26/8). PKK dilaksanakan di ruang virtual Zoom atau Google Meet dengan dua Panitia Pemilihan Raya (Papera) yang menjadi penanggung jawab tiap kelas. Setiap penanggung jawab bertugas mengurusi jalannya PKK kelas terkait mulai dari penentuan jadwal PKK, pelaksanaan PKK, hingga pengumpulan berkas yang diperlukan (berita acara pemilihan struktur organisasi kelas dan surat pernyataan ketua kelas).\n\n',
            paragraph_2: 'Susunan acara pada pelaksanaan PKK adalah sebagai berikut:\n',
            paragraph_3: '(1) Pembukaan dan doa,\n(2) pembacaan SOP Pemilihan Ketua Kelas (ditambah sosialisasi Pemira 2021 khusus kelas tingkat I),\n(3) pemanggilan calon ketua kelas,\n(4) penyampaian visi dan misi dari setiap calon ketua kelas,\n(5) pemungutan suara melalui Google Formulir,\n(6) pengumuman perolehan suara,\n(7) pemilihan perangkat kelas inti, serta\n(8) penutupan dan doa.\n\n',
            paragraph_4: 'Sebanyak 64 kelas telah memiliki ketua kelas serta perangkat inti (BPH) kelas masing-masing. Ketua kelas terpilih sekaligus menjadi perwakilan kelas sebagai anggota Dewan Perwakilan Mahasiswa (DPM) periode 2021/2022 Adapun rincian struktur organisasi setiap kelas yang distandardisasikan adalah: (i) satu orang ketua kelas, (ii) satu orang wakil ketua kelas, (iii) satu orang sekretaris, dan (iv) satu orang bendahara.\n\nSegenap Papera mengucapkan selamat dan semangat mengemban amanah kepada BPH Kelas Tingkat I-IV Terpilih Periode Kepengurusan 2021/2022. \n\n',
            paragraph_5: 'Pantau terus rangkaian kegiatan Pemilihan Raya tahun 2021 dengan mengikuti akun Instagram @pemirastis!'
        },
        paragraph_add:'',
        paragraph_footer:'',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 9,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1631538365_063516e4ed008cd4381f.png',
        date: '13 September 2021',
        title: 'Musyawarah Besar I DPM Polstat STIS Periode 2021 2022',
        excerpt: 'Musyawarah Besar I Dewan Perwakilan Mahasiswa (DPM) Polstat STIS periode 2021/2022 telah dilaksanakan pada Sabtu (04/09). Seperti tahun lalu, Musyawarah Besar...',
        description: {
            paragraph_1: 'Musyawarah Besar I Dewan Perwakilan Mahasiswa (DPM) Polstat STIS periode 2021/2022 telah dilaksanakan pada Sabtu (04/09). Seperti tahun lalu, Musyawarah Besar kali ini dilakukan secara daring melalui Zoom dan dihadiri seluruh anggota DPM periode 2021/2022 serta beberapa Panitia Pemilihan Raya (Papera) yang bertugas. Ada tiga pimpinan sidang yang memimpin jalannya Musyawarah Besar yakni Riva Adli Dzil Ikram, Muhammad Gozali Yahya, dan Shafira Nuraulia. Agenda Musyawarah Besar adalah menentukan 3 calon Ketua DPM periode 2021/2022 dari 6 bakal calon terpilih. \n\n',
            paragraph_2: 'Adapun 6 bakal calon terpilih yang telah lolos seleksi berkas adalah sebagai berikut:\n',
            paragraph_3: '1. Muchammad Gagah Agum Fanani\n2. Andi Alfitra Putra Fadila\n3. Muhammad Nur Megantoro\n4. Muhammad Ferdi\n5. Zahlul Fuadi\n6. Mochammad Nafi Dzakwan\n\n',
            paragraph_4: 'Setelah 6 bakal calon terpilih melakukan perkenalan, mereka kemudian dipindahkan ke dalam breakout room. Para anggota DPM periode 2021/2022 menyampaikan pendapat mereka tentang keenam bakal calon terpilih yang digunakan sebagai bahan pertimbangan. Hasil dari Musyawarah Besar I ini menghasilkan 3 calon Ketua DPM periode 2021/2022 yakni\n',
            paragraph_5: 'Penentuan Ketua DPM periode 2021/2022 akan dilaksanakan pada Musyawarah Besar selanjutnya. Sampai jumpa di Musyawarah Besar II DPM periode 2021/2022. Pantau seluruh kegiatan Pemilihan Raya melalui instagram @pemirastis.'
        },
        paragraph_add: '1. Andi Alfitra Putra Fadila\n2. Muhammad Nur Megantoro\n3. Zahlul Fuadi\n\n',
        paragraph_footer:'',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 10,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1631538950_f606746ecc0d0f0e70cf.png',
        date: '13 September 2021',
        title: 'Musyawarah Besar II DPM Polstat STIS Periode 2021 2022',
        excerpt: 'Musyawarah Besar I Dewan Perwakilan Mahasiswa (DPM) Polstat STIS periode 2021/2022 telah dilaksanakan pada Minggu (12/09) dengan dihadiri seluruh anggota...',
        description: {
            paragraph_1: 'Musyawarah Besar I Dewan Perwakilan Mahasiswa (DPM) Polstat STIS periode 2021/2022 telah dilaksanakan pada Minggu (12/09) dengan dihadiri seluruh anggota DPM periode 2021/2022 dan Panitia Pemilihan Raya (Papera) yang bertugas. Musyawarah besar II diagendakan untuk menindaklanjuti pemilihan Ketua DPM periode 2021/2022 dan dilakukan secara daring melalui media Zoom.\n\n',
            paragraph_2: 'Kegiatan ini diawali dengan penyampaian program kerja dan tanya jawab dengan audience dan bakal calon terpilih pada Mubes I kemarin, yakni:\n\n',
            paragraph_3: '1. Andi Alfitra Putra Fadila\n2. Muhammad Nur Megantoro\n3. Zahlul Fuadi\n\n',
            paragraph_4: 'Dari hasil penyampaian proker oleh ketiga calon tersebut maka ditetapkan Ketua DPM periode 2021/2022 yaitu, Andi Alfitra Putra Fadila (4SE5).\n\n',
            paragraph_5: 'Untuk itu, kami mewakili segenap mahasiswa/i Polstat STIS mengucapkan selamat dan semangat kepada Ketua DPM periode 2021/2022. Semoga bisa mengemban amanah dengan baik dan merealisasikan fungsi DPM sebagai badan legislatif mahasiswa yang kuat dan martabat.\n\nJangan lupa pantau seluruh kegiatan Pemilihan Raya melalui instagram @pemirastis dan siapkan diri kalian untuk pesta demokrasi Polstat STIS.',
        },
        paragraph_add:'',
        paragraph_footer:'',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 11,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1662252162_431bfc766444f3fcb335.jpg',
        date: '3 September 2022',
        title: 'Publikasi Pemilihan Raya Cakawaka Sema 2022 2023 Putaran Pertama',
        excerpt: 'Pemilihan Ketua Sema Periode 2022/2023 putaran pertama telah dilaksanakan selama 2 hari, yaitu sejak tanggal 29 Agustus 2022 hingga 30 Agustus 2022. Pemilihan ini...',
        description: {
            paragraph_1: 'Pemilihan Ketua Sema Periode 2022/2023 putaran pertama telah dilaksanakan selama 2 hari, yaitu sejak tanggal 29 Agustus 2022 hingga 30 Agustus 2022. Pemilihan ini dilaksanakan secara online melalui website Pemira (pemira.stis.ac.id). Seluruh mahasiswa Politeknik Statistika STIS melaksanakan pemilihan sesuai jadwal yang telah ditentukan.\n\n',
            paragraph_2: 'Selanjutnya pada Hari Jum’at, 02 September 2022, dilaksanakan publikasi resmi hasil Pemira putaran pertama tersebut secara offline, tepatnya di gedung 2 Politeknik Statistika STIS ruang 266. Publikasi tersebut dihadiri oleh paslon, perwakilan ormawa, dan para timses.\n\nDari 2115 mahasiswa, terdapat 2100 suara yang masuk (99.29%). Hasil yang diperoleh dari tiap-tiap paslon adalah sebagai berikut.\n',
            paragraph_3: 'Paslon 01\nCalon Ketua		: Muhammad Arfi Wahyudi\nCalon Wakil Ketua	: Anugerah Surya Pramana\nJumlah Suara		: 756 suara\nPersentase		: 36.00%\nPaslon 02\nCalon Ketua		: Gestyan Ramadhan\nCalon Wakil Ketua	: Kamal Maulana Alfi\nJumlah Suara		: 728 suara\nPersentase		: 34.67%\nPaslon 03\nCalon Ketua		: Farhan Satria Aditama\nCalon Wakil Ketua	: Kautsar Hilmi Izzuddin\nJumlah Suara		: 616 suara\nPersentase		: 29.33%\n\n',
            paragraph_4: 'Karena belum terdapat paslon yang memiliki lebih dari 50% suara, maka akan dilaksanakan Pemilihan Raya putaran kedua untuk memilih paslon nomor urut 01 atau 02. Pemilihan ini pun dilaksanakan secara offline pada tanggal 5-6 September mendatang. Dengan adanya Pemilihan Raya putaran kedua ini, diharapkan akan menghasilkan ketua-wakil ketua Sema terbaik untuk periode 2022/2023.\n\n',
            paragraph_5: ''
        },
        paragraph_add:'',
        paragraph_footer:'Pemira 2022\n\nPemilih Cerdas, Pemimpin Berkualitas!\n\n-----------------------------------------------------\n\nInstagram : @pemirastis',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 12,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1662552369_1ddbfe224f8c501fcaec.jpg',
        date: '7 September 2022',
        title: 'Musyawarah Final Dewan Perwakilan Mahasiswa Periode 2022 2023',
        excerpt: 'Pada Senin, 05 September 2022, seluruh anggota Dewan Perwakilan Mahasiswa Politeknik Statistika STIS periode 2022/2023 telah menyelenggarakan  kegiatan Musyawarah...',
        description: {
            paragraph_1: 'Pada Senin, 05 September 2022, seluruh anggota Dewan Perwakilan Mahasiswa Politeknik Statistika STIS periode 2022/2023 telah menyelenggarakan  kegiatan Musyawarah Final DPM yang dipandu oleh Panitia Pemilihan Raya (Papera) yang bertugas. Kegiatan ini dimulai pada pukul 16.15 WIB dan bertempat di auditorium kampus Politeknik Statistika STIS.\n\n',
            paragraph_2: 'Musyawarah ini ialah lanjutan dari agenda Musyawarah Besar DPM I yang telah dilakukan sebelumnya serta bertujuan untuk pelaksanaan pemilihan Ketua DPM periode 2022/2023. Berdasarkan hasil Musyawarah Besar DPM I, diperoleh tiga nama yang dicalonkan sebagai ketua. Ketiga nama tersebut di antaranya adalah:\n\n',
            paragraph_3: '1. Aldi Firmansyah (4SE3)\n2. Muhammad Riza Fakhrulrizqi (4SK4)\n3. Syaikhul ‘Ibad (4SE2)\n\n',
            paragraph_4: 'Proses Musyawarah Final ini diawali dengan pembukaan, pengenalan ketiga calon ketua DPM sekaligus penyampaian visi-misi dari setiap calon, diskusi dan tanya jawab, musyawarah final, pembacaan keputusan hasil musyawarah, pembacaan berita acara, serta diakhiri dengan penutupan sekaligus doa. Berdasarkan hasil musyawarah final yang telah dilakukan, Muhammad Riza Fakhrulrizqi (4SK4) telah ditetapkan sebagai Ketua DPM terpilih periode 2022/2023.\n\nMaka dari itu, kami dan segenap mahasiswa/i Polstat STIS mengucapkan selamat dan semangat bertugas bagi Ketua DPM terpilih. Semoga dapat menjalankan amanah dan tanggung jawab ini dengan sebaik-baiknya dalam satu tahun ke depan.\n\n',
            paragraph_5: ''
        },
        paragraph_add:'',
        paragraph_footer:'Pemira 2022\n\nPemilih Cerdas, Pemimpin Berkualitas!\n\n-----------------------------------------------------\n\nInstagram : @pemirastis',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 13,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1663162795_85e31a12f8132b614ffe.jpg',
        image_2: '',
        date: '19 September 2022',
        title: 'Publikasi Pemilihan Raya Cakawaka Sema 2022 2023 Putaran Kedua',
        excerpt: 'Pemilihan Ketua-Wakil Ketua Sema Periode 2022/2023 putaran kedua telah dilaksanakan selama dua hari, yaitu pada tanggal 5 - 6 September 2022. Berbeda dengan pemilihan...',
        description: {
            paragraph_1: 'Pemilihan Ketua-Wakil Ketua Sema Periode 2022/2023 putaran kedua telah dilaksanakan selama dua hari, yaitu pada tanggal 5 - 6 September 2022. Berbeda dengan pemilihan putaran pertama, pemilihan putaran kedua kali ini dilaksanakan secara hybrid, peserta datang secara langsung ke TPS (Tempat Pemungutan Suara) yang berada di Auditorium Politeknik Statistika STIS dan mengakses website resmi Pemira untuk melakukan voting dengan menggunakan perangkat yang telah disediakan oleh panitia pemilihan raya. Pemilihan raya dibagi dalam beberapa sesi menurut kelas agar pelaksanaannya lebih kondusif.\n\n',
            paragraph_2: 'Kemudian, pada hari Jumat, 9 September 2022, telah dilakukan publikasi hasil pemilihan raya putaran kedua secara resmi melalui live Instagram dari akun Pemira (@pemirastis). Hasil yang didapatkan, dari 2.115 mahasiswa, terdapat 2.063 suara yang masuk atau sekitar 97,54% dari total seluruh mahasiswa Politeknik Statistika STIS. Hasil perolehan suara untuk tiap-tiap pasangan calon adalah sebagai berikut:\n\n',
            paragraph_3: 'Paslon 01\nCalon Ketua		: Muhammad Arfi Wahyudi\nCalon Wakil Ketua	: Anugerah Surya Pramana\nJumlah Suara		: 922 suara\nPersentase		: 44.69%\nPaslon 02\nCalon Ketua		: Gestyan Ramadhan\nCalon Wakil Ketua	: Kamal Maulana Alfi\nJumlah Suara		: 1.141 suara\nPersentase		: 55.31%\n\n',
            paragraph_4: 'Dengan demikian, pasangan calon nomor urut 02 resmi menjadi Pasangan Kawaka Sema terpilih periode 2022/2023 karena telah mengantongi lebih dari 50% suara masuk. Selamat kepada pasangan Kawaka Sema terpilih, semoga dapat menjalankan amanahnya dengan penuh tanggung jawab.\n\n',
            paragraph_5: ''
        },
        paragraph_add:'',
        paragraph_footer:'Pemira 2022\n\nPemilih Cerdas, Pemimpin Berkualitas!\n\n-----------------------------------------------------\n\nInstagram : @pemirastis',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 14,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1663990822_a47f93e4175d7859f5c8.jpg',
        date: '23 September 2022',
        title: 'Pelantikan DPM dan Kawaka Sema Periode 2022 2023',
        excerpt: 'Setelah melalui rangkaian proses seleksi, DPM dan Ketua-Wakil Ketua Sema terpilih Politeknik Statistika STIS periode 2022/2023 pun resmi dilantik. Kegiatan pelantikan ini...',
                description: {
            paragraph_1: 'Setelah melalui rangkaian proses seleksi, DPM dan Ketua-Wakil Ketua Sema terpilih Politeknik Statistika STIS periode 2022/2023 pun resmi dilantik. Kegiatan pelantikan ini dilaksanakan secara offline pada Selasa, 20 September 2022 di ruang auditorium Politeknik Statistika STIS. Berdasarkan Surat Keputusan Direktur, Dr. Erni Tri Astuti, M. Math, terdapat 62 mahasiswa yang dilantik, di antaranya:\n\n',
            paragraph_2: '',
            paragraph_3: 'Dewan Perwakilan Mahasiswa\n1. Ketua		: Muhammad Riza Fakhrulrizki (4SK4)\n2. Wakil Ketua	: Alwan Rahmana Subian (3SD2)\n3. Anggota DPM yang berjumlah 58 orang\n\nSenat Mahasiswa\n1. Ketua		: Gestyan Ramadhan (4SI2)\n2. Wakil Ketua	: Kamal Maulana Alfi (3SE4)\n\n',
            paragraph_4: 'Selain dihadiri oleh mahasiswa yang dilantik, upacara ini juga dihadiri oleh beberapa perwakilan Dosen Politeknik Statistika STIS. Pada pelaksanaannya, Satuan Penegak Disiplin (SPD) bertindak sebagai petugas upacara dan Bapak Yunarso Anang, Ph.D sebagai Pembina. Upacara pelantikan ini berlangsung secara lancar dan khidmat dari awal hingga akhir.\n\n',
            paragraph_5: 'Kami segenap mahasiswa Politeknik Statistika STIS mengucapkan selamat kepada DPM dan Ketua-Wakil Ketua Sema yang telah dilantik. Semoga dapat bertanggung jawab terhadap amanah yang diemban hingga akhir periode kepengurusan.\n\n',
        },
        paragraph_add:'',
        paragraph_footer:'Pemira 2022\n\nPemilih Cerdas, Pemimpin Berkualitas!\n\n-----------------------------------------------------\n\nInstagram : @pemirastis',
        tags: 'DPM, SEMA',
        author: 'HPD',
    },
];