export const mockdata = [
    {
        id: 1,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602569085_7c3e90155a66a2f220b7.png',
        date: '13 Oktober 2020',
        title: 'Pasangan Calon Ketua Wakil Ketua SEMA Polstat STIS',
        excerpt: 'Rabu (29/7), telah dibuka pendaftaran Calon Ketua dan Wakil Ketua Senat Mahasiswa Politeknik Statistika STIS. Calon Ketua Senat Mahasiswa merupakan mahasiswa tingkat 4 sedangkan Calon Wakil Ketua Senat Mahasiswa merupakan mahasiswa tingkat 3. Seluruh mahasiswa tingkat 3 dan 4 yang memenuhi syarat untuk...',
        description: '',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 2,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602580730_bb96681ea32afbfd92a5.png',
        date: '13 Oktober 2020',
        title: 'Tahapan Seleksi Cakawaka Sema',
        excerpt: 'Sebelum memasuki masa kampanye Cakawaka Sema, telah dilaksanakan berbagai tahapan seleksi untuk mendapatkan bakal calon terbaik. Tahap pertama berupa seleksi berkas yang diikuti oleh seluruh paslon yang akan mengikuti Pemira 2020. Berkas dikumpulkan dalam bentuk softfile yang terdiri dari transkip nilai...',
        description: '',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 3,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602584692_524a9dc1caa5953b0fde.png',
        date: '13 Oktober 2020',
        title: 'Pemilihan Ketua Kelas atau Anggota DPM Periode 2020',
        excerpt: 'Pemilihan ketua kelas telah berlangsung mulai dari tanggal 31 Agustus hingga 8 September untuk tingkat 2-4 dan 6 hingga 7 Oktober untuk tingkat 1. Prosedur yang dilaksanakan adalah calon ketua kelas mendaftar di Google Form yang disediakan panitia beberapa hari sebelum pemilihan. Kemudian PJ masing-masing...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 4,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1602588118_0faee0d8cf331e4d6918.png',
        date: '13 Oktober 2020',
        title: 'Kampanye Akbar 2020',
        excerpt: 'Dalam memilih seorang pemimpin, kita harus mengenal siapa calon pemimpin kita dengan mengetahui visi misi, progam, dan janji mereka. Dengan mengetahui siapa calon pemimpin kita, tentu kita akan yakin dan tidak menyesal ketika memilih mereka dalam Pemilihan Raya 2020 nanti. Bagaimana cara kita mengenal...',
        description: '',
        tags: 'SEMA',
        author: 'HPD',
    },
    {
        id: 5,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1607072778_30f25fc3d4f096d5ce1a.png',
        date: '04 Desember 2020',
        title: 'Musyawarah DPM dan Hasil Pemilihan Ketua DPM Periode 2020-2021',
        excerpt: 'Dewan Perwakilan Mahasiswa (DPM) merupakan perubahan bentuk dari Badan Perwakilan Mahasiswa (BPM) dan Majelis Permusyawaratan Mahasiswa (MPM) yang menjalankan fungsi legislatif Imapolstat dan salah satu pemegang kekuasaan tertinggi dalam Imapolstat melalui Sidang Umum DPM. DPM menyalurkan aspirasi dari...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 6,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1627698105_2403e7b73b60343e5d0c.jpg',
        date: '30 Juli 2020',
        title: 'DPM Polstat STIS Tetapkan Ketetapan mengenai Pemira',
        excerpt: 'Dewan Perwakilan Mahasiswa (DPM) resmi menetapkan Ketetapan Dewan Perwakilan Mahasiswa Politeknik Statistika STIS Nomor 003/DPM/2021 tentang Pemilihan Raya pada 17 Juli 2021. Ketetapan tersebut ditetapkan oleh Ketua DPM periode 2020/2021, Septriyan Machsus. Selain ditetapkan, Tap DPM Polstat STIS Nomor...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 7,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1629349447_1a2d24cd3c6a4dc6f0a6.jpeg',
        date: '19 Agustus 2021',
        title: 'Peraturan Panitia Pemilihan Raya tentang Penyelenggaran Pemira',
        excerpt: 'Senin (02/08) Ketua Panitia Pemilihan Raya (Papera), Andi Alfitra Putra Fadila menetapkan peraturan Papera tentang Penyelenggaraan Pemilihan Raya (Pemira) Nomor: 001/PAPERA/2021. Peraturan tersebut resmi diundangkan oleh ekretaris I Dewan Perwakilan Mahasiswa, Neisya Aulia Fijri. Peraturan Papera...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
    {
        id: 8,
        image:  'https://pemira.stis.ac.id/assets/img/cover/1630813091_277e32d71b0942fd63a4.png',
        date: '04 September 2021',
        title: 'Pemilihan Ketua Kelas atau Anggota DPM Periode 2021',
        excerpt: 'Periode Pemilihan Ketua Kelas (PKK) Tingkat I-IV Periode 2021/2022 telah berlangsung selama empat hari, sejak Senin (23/8) hingga Kamis (26/8). PKK dilaksanakan di ruang virtual Zoom atau Google Meet dengan dua Panitia Pemilihan Raya (Papera) yang menjadi penanggung jawab tiap kelas. Setiap penanggung...',
        description: '',
        tags: 'DPM',
        author: 'HPD',
    },
];